modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="minerals_and_stuff"
version="1.0.0"
displayName="Minerals and stuff"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Molianov, MCreator"

[[dependencies.minerals_and_stuff]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



